task 5 global exception handler build success
MolchanovAlexander/book-store-webapp pull request #5
Opened 2024-04-30 09:10 UTC by MolchanovAlexander

2024-04-30 09:50 UTC, VlasenkoYevhenii approved these changes
lgfm!

2024-04-30 16:29 UTC, makaroshyna approved these changes
GJ

2024-04-30 16:29 UTC, makaroshyna commented on src/main/java/com/example/bookstorewebapp/controller/BookController.java
You could also add @Valid to updateBook method.

2024-05-01 13:18 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-05-01 13:18 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/dto/CreateBookRequestDto.java
> +    @Pattern(regexp = "^\\d{13}$", message = "The ISBN must contain 13 digits")
I believe there is specific annotation to validate ISBN

2024-05-01 13:18 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/exception/CustomGlobalExceptionHandler.java
> +    ) {
Please add methods to handle other exceptions that could occur in your code

2024-05-01 13:18 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/repository/book/BookSpecificationBuilder.java
> +    private final SpecificationProviderManager<Book> bookSpecificationProviderManager;
Is this changed related to task?

2024-05-02 09:30 UTC, yevheniisynytsia approved these changes

2024-05-02 09:30 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstorewebapp/dto/CreateBookRequestDto.java
> +    @Isbn
there is `@ISBN` in hibernate validation https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/ISBN.html

but you can leave custom if you like

2024-05-02 09:30 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstorewebapp/dto/CreateBookRequestDto.java
> +    @Size(min = 2, max = 255)
adding messages to the constraints would be great

2024-05-02 09:34 UTC, MolchanovAlexander commented on src/main/java/com/example/bookstorewebapp/dto/CreateBookRequestDto.java
> +    @Size(min = 2, max = 255)
But they have it inside by default and add to response values like name must have from 2 to 255 symbols.

2024-05-02 11:00 UTC, merged