Book task 6
MolchanovAlexander/book-store-webapp pull request #6
Opened 2024-05-02 13:31 UTC by MolchanovAlexander

2024-05-02 15:25 UTC, azzilian reviewed
Gj!

2024-05-03 10:41 UTC, yevheniisynytsia requested changes
Great job! Left one comment

2024-05-03 10:41 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstorewebapp/controller/BookController.java
>      public List<BookDto> search(BookSearchParameters searchParameters) {
let's add pageable here as well

2024-05-03 14:42 UTC, andrii-hoienko approved these changes
Gj!

2024-05-04 06:16 UTC, merged