build success
MolchanovAlexander/book-store-webapp pull request #7
Opened 2024-05-06 09:38 UTC by MolchanovAlexander

2024-05-06 14:05 UTC, andrii-hoienko requested changes
Nice, left some questions and comments

2024-05-06 14:05 UTC, andrii-hoienko commented on pom.xml
> +
```suggestion
```

2024-05-06 14:05 UTC, andrii-hoienko commented on pom.xml
> +        </dependency>
What is that and why it is necessary? It is not used

2024-05-06 14:05 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/controller/AuthenticationController.java
> +@RequestMapping(value = "/api/register")
```suggestion
@RequestMapping(value = "/api/auth")
```

2024-05-06 14:05 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/controller/AuthenticationController.java
> +    @ResponseStatus(value = HttpStatus.CREATED)
```suggestion
@RequestMapping("/register")
    @ResponseStatus(value = HttpStatus.CREATED)
```

2024-05-06 14:05 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/service/authentication/impl/AuthenticationServiceImpl.java
> +        if (userRepository.getByEmail(requestDto.getEmail()) != null) {
```suggestion
        if (userRepository.getByEmail(requestDto.getEmail()).isPresent) {
```

2024-05-06 14:05 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
```suggestion
```

2024-05-06 14:05 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/repository/user/UserRepository.java
> +    User getByEmail(String email);
```suggestion
    Optional<User> getByEmail(String email);
```

2024-05-06 14:05 UTC, andrii-hoienko commented on src/main/java/com/example/bookstorewebapp/validation/FieldMatch.java
> +public @interface FieldMatch {
Optional: Actually your annotation works only with password and repeatPassword, so FieldMatch is bad name, because it should work with any 2 fields, so it is better to make it work as expected or rename

2024-05-07 07:23 UTC, MolchanovAlexander commented on src/main/java/com/example/bookstorewebapp/validation/FieldMatch.java
> +public @interface FieldMatch {
I totally agree with you, but this is required by task .

2024-05-08 15:10 UTC, andrii-hoienko approved these changes
Good job!

2024-05-08 15:54 UTC, merged